name: mausam
description: A simple weather app demonstrating api integration.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Enables making HTTP requests, essential for fetching data from APIs
  http: ^0.13.6

  # Provides functionality to determine the device's location coordinates
  geolocator: ^10.1.0

  # Translates latitude and longitude coordinates into readable location addresses
  geocoding: ^2.1.1

  # Integrates high-quality animations via JSON files
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
